pops_genos_ids:
	curl -L -o 1kg_nygc_trios_removed_All_pops_geno_ids_pops.csv https://zenodo.org/record/8157131/files/1kg_nygc_trios_removed_All_pops_geno_ids_pops.csv?download=1

AFR:
	curl -L -o AFR.precision.tar.gz https://zenodo.org/record/8157131/files/AFR.precision.tar.gz?download=1

AMR:
	curl -L -o AMR.precision.tar.gz https://zenodo.org/record/8157131/files/AMR.precision.tar.gz?download=1

EAS:
	curl -L -o EAS.precision.tar.gz https://zenodo.org/record/8157131/files/EAS.precision.tar.gz?download=1

EUR:
	curl -L -o EUR.precision.tar.gz https://zenodo.org/record/8157131/files/EUR.precision.tar.gz?download=1

SAS:
	curl -L -o SAS.precision.tar.gz https://zenodo.org/record/8157131/files/SAS.precision.tar.gz?download=1

genos_chr21_chr22
	curl -L -o genos_chr21_22.tar.gz https://zenodo.org/record/8157131/files/genos_chr21_22.tar.gz?download=1

ldgms:
	curl -L -o ldgms.tar.gz https://zenodo.org/record/8157131/files/ldgms.tar.gz?download=1

snplists:
	curl -L -o snplists_GRCh38positions.tar.gz https://zenodo.org/record/8157131/files/snplists_GRCh38positions.tar.gz?download=1

tree_seqs:
	curl -L -o tree_seqs.tar https://zenodo.org/record/8157131/files/tree_seqs.tar?download=1

ukb:
	curl -L -o ukb.tar https://zenodo.org/record/8157131/files/ukb.tar?download=1

download_all: pops_genos_ids AFR AMR EAS EUR SAS
